name: haskell-backend
version: 0.1.0.0
license: BSD-3-Clause

executables:
  haskell-backend:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -Wall
    dependencies:
      - base >= 4.14 && < 5
      - servant-server
      - wai
      - warp
