apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
        - name: python-backend
          image: ghcr.io/alberto-kali/lms-python-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: LMS_CLICKHOUSE_HOST
              value: clickhouse
            - name: LMS_CLICKHOUSE_PORT
              value: "8123"
            - name: LMS_CLICKHOUSE_DATABASE
              value: lms
            - name: LMS_CLICKHOUSE_USER
              value: default
            - name: LMS_CLICKHOUSE_PASSWORD
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: python-backend
spec:
  selector:
    app: python-backend
  ports:
    - port: 8000
      targetPort: 8000
